name: online-ticket-booking-system

services:
  api:
    build: .
    entrypoint : ["sh","/online-ticket-booking-system/entrypoint.sh"]
    command: ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    container_name: fastapi_app_container
    ports:
      - "8000:8000"
      - "5678:5678"
    env_file:
      - .env.docker
    restart: always
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./app
          target: /online-ticket-booking-system/app
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./uv.lock

  db:
    image: postgres:16-alpine
    ports:
      - "5431:5432"
    container_name: postgres_container
    env_file:
      - .env.docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:alpine
    container_name: redis_container
    volumes:
      - redis_data:/data
    restart: always

  elasticsearch:
    image: elasticsearch:9.2.7
    container_name: elasticsearch_container
    env_file:
      - .env.docker
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    restart: always
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9200"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
  elastic_data: