"""v5_change_booking_seats_from_array_to_string

Revision ID: 8aa887aa9906
Revises: d086446bd772
Create Date: 2026-04-09 14:31:51.953399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aa887aa9906'
down_revision: Union[str, Sequence[str], None] = 'd086446bd772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###