"""recreate_booked_seats_map

Revision ID: b03be9cea85d
Revises: 99e06eb1726a
Create Date: 2026-04-13 10:15:24.728923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b03be9cea85d'
down_revision: Union[str, Sequence[str], None] = '99e06eb1726a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booked_seats_map',
    sa.Column('seats_number', sa.String(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('show_id', sa.UUID(), nullable=False),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booked_seats_map_booking_id'), 'booked_seats_map', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booked_seats_map_show_id'), 'booked_seats_map', ['show_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booked_seats_map_show_id'), table_name='booked_seats_map')
    op.drop_index(op.f('ix_booked_seats_map_booking_id'), table_name='booked_seats_map')
    op.drop_table('booked_seats_map')
    # ### end Alembic commands ###