"""v3_change_genre_field_add_imdb_id_field_in_movie

Revision ID: b4be2270c18c
Revises: 989d15a09c65
Create Date: 2026-04-02 18:42:05.181492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4be2270c18c'
down_revision: Union[str, Sequence[str], None] = '989d15a09c65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('imdb_id', sa.String(), nullable=False))
    op.alter_column('movies', 'genre',
               existing_type=postgresql.ARRAY(postgresql.ENUM('ACTION', 'SCIFI', 'COMEDY', 'THRILLER', 'ROMANCE', 'DRAMA', 'ANIMATION', 'CRIME', 'HORROR', 'FANTASY', 'OTHER', name='movie_genre_enum')),
               type_=sa.String(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'movies', ['imdb_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='unique')
    op.alter_column('movies', 'genre',
               existing_type=sa.String(),
               type_=postgresql.ARRAY(postgresql.ENUM('ACTION', 'SCIFI', 'COMEDY', 'THRILLER', 'ROMANCE', 'DRAMA', 'ANIMATION', 'CRIME', 'HORROR', 'FANTASY', 'OTHER', name='movie_genre_enum')),
               existing_nullable=False)
    op.drop_column('movies', 'imdb_id')
    # ### end Alembic commands ###