"""v4_normalized_booking_table

Revision ID: d086446bd772
Revises: b4be2270c18c
Create Date: 2026-04-08 14:14:27.020259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd086446bd772'
down_revision: Union[str, Sequence[str], None] = 'b4be2270c18c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booked_seats_map',
    sa.Column('seats_number', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('show_id', sa.UUID(), nullable=False),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booked_seats_map_booking_id'), 'booked_seats_map', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booked_seats_map_show_id'), 'booked_seats_map', ['show_id'], unique=False)
    op.drop_column('bookings', 'seats_array')
    op.add_column('shows', sa.Column('category_pricing', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'category_pricing')
    op.add_column('bookings', sa.Column('seats_array', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_booked_seats_map_show_id'), table_name='booked_seats_map')
    op.drop_index(op.f('ix_booked_seats_map_booking_id'), table_name='booked_seats_map')
    op.drop_table('booked_seats_map')
    # ### end Alembic commands ###